spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: deli
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
