spring:
    datasource:
        url: jdbc:mysql://localhost:3306/delivery
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: deli
        password: password
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
        generate-ddl: true
        hibernate:
          ddl-auto: update
          use-new-id-generator-mappings: true
        properties:
          hibernate:
            format_sql: true
            show_sql: true

    redis:
        host: localhost
        port: 6379

sms:
    auth-api:
        apikey: (enter your api key)
        secret: (enter your secret key)
        sender: (enter a representative sender number)
        type: (enter sms type to send)

auth:
    jwt:
        secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
        accessduration: 30
        refreshduration: 10080
